### ISSUE TITLE
Latest tweets better integration

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/islemag#101]
@cristian-ungureanu @rodica-andronache ar trebui adaugat un mic CSS pentru o mai buna integrare a plugin-ului pentru twitter. 

Ar fi ideal ca textul tweet-ului sa arate la fel ca cel din widgeturile din footer.

<img width="887" alt="skitch" src="https://cloud.githubusercontent.com/assets/6906834/13847304/df9b1d88-ec4c-11e5-87bd-768f02fbd900.png">

**Comment by cristian-ungureanu** [comment]
@mileamadalin , pluginul pe care l-ai instalat in demo WP Twitter Feeds ( http://vivacityinfotech.net/wordpress/plugins/wp-twitter-feeds-wordpress-plugin-by-vivacity/ ) nu mai exista pe wordpress.org, ar trebui gasit alt plugin ... nu cred ca are rost sa oferim compatibilitate pentru el atata timp cat n-ai de unde sa-l descarci ( https://wordpress.org/plugins/wp-twitter-feeds/ )
