### ISSUE TITLE
Spatiere imagini din articol

### ISSUE THREAD

**Issue by sab2ina** [Codeinwp/islemag#116]
In interiorul articolului, sa bagam mai mult spatiu deasupra imaginilor integrate in text

**Comment by rodica-andronache** [comment]
@mileamadalin aici cred ca te poti ocupa tu, nu? sa mai lasi niste spatii in continut pe demo

**Comment by ineagu** [comment]
@rodica-andronache nu asta era problema, ideea era ca imaginea, tag-ul IMG din posts nu are padding deloc, noi aranjam pe demo, dar userilor tot rau o sa le mearga :D

**Comment by rodica-andronache** [comment]
dap, asa e :D
