### ISSUE TITLE
Spatiere banner

### ISSUE THREAD

**Issue by sab2ina** [Codeinwp/islemag#117]
In interiorul unui articol sa avem mai mult spatiu deasupra si sub bannerul care e intercalat in text

**Comment by rodica-andronache** [comment]
@mileamadalin aici poti modifica tu pe demo te rog?

**Comment by ineagu** [comment]
@rodica-andronache cred ca e aceeasi problema ca la imagine.

**Comment by ineagu** [comment]
adica si bannerul tot imagine e
