### ISSUE TITLE
w.org review

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/islemag#120]
@cristian-ungureanu @rodica-andronache 

Am primit review de la w.org : https://themes.trac.wordpress.org/ticket/29267, nu arata ideal, uitati ce putem face  : 
1. Rezolva totul asa cum zic ei, cat mai rapid ( mai ales faza cu reading )
2. Publicat ideal saptamana asta tema pe themeisle+codeinwp + justfreethemes

**Comment by rodica-andronache** [comment]
@ineagu pentru pagina de themeisle avem imaginile facute pt varianta de template vechi http://themeisle.com/themes/islemag/. Lasam asa si publicam sau facem cu template-ul nou? eu ma gandeam sa facem cu asta nou

**Comment by ineagu** [comment]
Tinand cont ca e tema free, cel vechi e ok.
