### ISSUE TITLE
Theme URI - page not found

### ISSUE THREAD

**Issue by cristian-ungureanu** [Codeinwp/islemag#124]
Theme URI is optional. If used, it is required to link to a page with information about the Theme. If a demonstration site is being used, the content must be related to the theme itself and not test data. Further to this from slack discussions, the page should be about the WordPress.org hosted theme, not a pure upsell landing page.
At time of review this link returned a Page not found. Please fix or remove the link.

**Comment by abaicus** [comment]
Am schimbat imaginile. Banuiesc ca putem publica. :)
