### ISSUE TITLE
ddSlick license

### ISSUE THREAD

**Issue by cristian-ungureanu** [Codeinwp/islemag#129]
You claim ddSlick is MIT licensed but I can't find evidence for that on the authors website. In fact folks are asking the author there to license it. Can you tell me where to find evidence for GPL compatibility? If not please remove the resource.

**Comment by cristian-ungureanu** [comment]
@ineagu , ddSlick is used based on a comment of its author:
![screenshot_2](https://cloud.githubusercontent.com/assets/9929553/14976030/c912a658-10ff-11e6-8725-f791ee055d60.png)
The comment can be found here https://github.com/prashantchaudhary/ddslick/issues/39

**Comment by ineagu** [comment]
ok, sa vb cu rodica sa lase chestia asta in comment cand pune update ( si
in readme )

On Tue, May 3, 2016 at 8:23 AM, cristian-ungureanu <notifications@github.com
> wrote:

> @ineagu <https://github.com/ineagu> , ddSlick is used based on a comment
> of its author:
> [image: screenshot_2]
> <https://cloud.githubusercontent.com/assets/9929553/14976030/c912a658-10ff-11e6-8725-f791ee055d60.png>
> The comment can be found here prashantchaudhary/ddslick#39
> <https://github.com/prashantchaudhary/ddslick/issues/39>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/islemag/issues/129#issuecomment-216447897>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
