### ISSUE TITLE
Use sane defaults 

### ISSUE THREAD

**Issue by cristian-ungureanu** [Codeinwp/islemag#130]
Use sane defaults and don’t write default setting values to the database.
It looks to me like default setting values for social links are being saved to the database.

Please explain what the id is for in the social links default table.

-Social links should not be shown if there is no link.
-Custom and widget demo content in the footer should not be there. You should not be creating any content after theme switch. Please remove this demo content.

ref: https://make.wordpress.org/themes/2016/03/31/what-is-demo-content/

**Comment by rodica-andronache** [comment]
@cristian-ungureanu @ineagu asta nu ar trebui rezolvata inainte sa publicam tema la noi ca sa nu mai avem apoi probleme?

**Comment by ineagu** [comment]
Ma gandesc ca schimband homepage am mai putea scapa dr ele ?

**Comment by rodica-andronache** [comment]
pai ar trebui sa scoatem tot, ca sigur o sa ne puna sa le scoatem

**Comment by ineagu** [comment]
Ok, putem lucra si la asta .
