### ISSUE TITLE
Space between widgets issue

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/islemag#137]
@rodica-andronache pare ca avem o problema cu spatierea dupa widgetu-ul de tags. 

Am adaugat o poza:

![skitch](https://cloud.githubusercontent.com/assets/6906834/15047145/26ce0470-12ec-11e6-89e7-9441316b3583.png)

**Comment by abaicus** [comment]
Note to self: 

`.tagcloud:after {
    clear:both;
    content:"";
    display:block;
}`
