### ISSUE TITLE
Menu problems on responsive

### ISSUE THREAD

**Issue by cristian-ungureanu** [Codeinwp/islemag#141]
![screenshot_2](https://cloud.githubusercontent.com/assets/9929553/15111264/9cb417ec-15ee-11e6-8dcf-676490044e0b.png)

**Comment by rodica-andronache** [comment]
@cristian-ungureanu for me the dropdown menu on mobile doesn't seam to work at all . Can you please check again?
![menu](https://cloud.githubusercontent.com/assets/3266155/15149511/73e92502-16d2-11e6-93f1-6919e03d246e.gif)

**Comment by rodica-andronache** [comment]
@cristian-ungureanu in header.php you should have theme_location' => 'islemag-primary'
and also, is not working for all resolutions. For example on 660px is not working
