### ISSUE TITLE
Change posts order on frontpage sections

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/islemag#144]
@ineagu what do you think it's the best solution here, to have options in customizer for this or to have filters that may be use in a child theme? I was thinking about filters

Source: https://secure.helpscout.net/conversation/200411056/0/

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , Ionut told me just to change post order in WP_Query settings, from ASC to DESC but I agree with you, filters would be a better option. Also, this is a duplicate of https://github.com/Codeinwp/islemag/issues/142

**Comment by ineagu** [comment]
I would sort DESC by default, no options. Filters might be a good idea as
well.

On Mon, May 9, 2016 at 2:59 PM, cristian-ungureanu <notifications@github.com
> wrote:

> @rodica-andronache <https://github.com/rodica-andronache> , Ionut told me
> just to change post order in WP_Query settings, from ASC to DESC but I
> agree with you, filters would be a better option. Also, this is a duplicate
> of #142 <https://github.com/Codeinwp/islemag/issues/142>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/islemag/issues/144#issuecomment-217857146>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by rodica-andronache** [comment]
ok,  @cristian-ungureanu then I would close this. This https://github.com/Codeinwp/islemag/issues/146 is the issue for the filters, maybe we'll add them at some point
