### ISSUE TITLE
Multiple Select on section for Category

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/islemag#152]
@rodica-andronache Cred ca ar trebui sa includem un multi select in Customizer -> Section -> Category.

Momentan avem un buton dropdown pentru a alege o categorie sau toate, dar nu putem exclude sau selecta doar doua category din trei.

Exemplu concret, pe demo-ul nostru avem o sectine de News de pe care as vrea sa scot sectiunea de Reviews si in rest sa ruleze toate celelalte, dar acest lucru nu este posibil. Stiu ca pot creea o categorie pe care o afisez acolo si am rezolvat problema, insa eu cred ca este o chestie importanta sa includem asa ceva in tema noastra, mai ales ca pe asta se bazeaza tema, pe continut.

@ineagu ce parere ai?

**Comment by ineagu** [comment]
nu cred ca este nevoie de asta, nu e o idee rea, dar ai posibilitatea de a
crea o categorie featured de ex.

2016-05-11 18:01 GMT+02:00 Madalin Milea <notifications@github.com>:

> @rodica-andronache <https://github.com/rodica-andronache> Cred ca ar
> trebui sa includem un multi select in Customizer -> Section -> Category.
>
> Momentan avem un buton dropdown pentru a alege o categorie sau toate, dar
> nu putem exclude sau selecta doar doua category din trei.
>
> Exemplu concret, pe demo-ul nostru avem o sectine de News de pe care as
> vrea sa scot sectiunea de Reviews si in rest sa ruleze toate celelalte, dar
> acest lucru nu este posibil. Stiu ca pot creea o categorie pe care o afisez
> acolo si am rezolvat problema, insa eu cred ca este o chestie importanta sa
> includem asa ceva in tema noastra, mai ales ca pe asta se bazeaza tema, pe
> continut.
>
> @ineagu <https://github.com/ineagu> ce parere ai?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/islemag/issues/152>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
