### ISSUE TITLE
Rename Advertisement areas

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/islemag#155]
http://prntscr.com/b51rtq

to be more clear that those sections appear only on frontpage

**Comment by oliverap** [comment]
Can you please describe WHERE on frontpage? I can only see Ad area 1 (after slider). I do not see 2, 3, 4 and 5

**Comment by rodica-andronache** [comment]
Hi @oliverap ,

I tested a bit and I too couldn't make those sections work. @cristian-ungureanu can you please investigate this?

Thanks

**Comment by CarolinaOP** [comment]
I'm having the same problem. It's not clear where they would appear and when I try to test, adding them content, there's no difference in the frontpage.

**Comment by rodica-andronache** [comment]
Hi,
These areas appear after each of the 5 frontpage sections. To be able to see them, you need to make sure you don't have any adblock on that page.
