### ISSUE TITLE
Html is getting into related posts excerpts 

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/islemag#164]
@cristian-ungureanu @abaicus I see that HTML is getting into related posts excerpts and it shouldn't happen : https://www.dropbox.com/s/70fg37c6tqu892r/Screenshot%202016-05-30%2013.47.21.png?dl=0

**Comment by cristian-ungureanu** [comment]
oh....forgot to put esc_html in excerpt

**Comment by cristian-ungureanu** [comment]
@ineagu , I can't replicate this issue, I've tested it on chrome and safari on windows and I also checked it on browserstack . Everything looks normal.

**Comment by cristian-ungureanu** [comment]
@abaicus , can you check this again please?

**Comment by abaicus** [comment]
Export the content from the dev2 site and import it back into your local wordpress instance. Looking again at it now, there might be no issue except the fact that the HTML tags have been inputted into the Wordpress Visual Editor. 

There might be no issue at all. 

![image](https://cloud.githubusercontent.com/assets/15010186/15678481/2b4b8b1a-2757-11e6-8272-25f31f4b952e.png)

**Comment by abaicus** [comment]
Can now confirm. Edited the post and added the dropcap to the text editor. Everything is ok. 
![image](https://cloud.githubusercontent.com/assets/15010186/15678592/951a7916-2757-11e6-9ee5-fb841657df57.png)

**Comment by ineagu** [comment]
ok, the issue was on dev2 :P

On Tue, May 31, 2016 at 4:46 PM, Andrei Băicuș <notifications@github.com>
wrote:

> Can now confirm. Edited the post and added the dropcap to the text editor.
> Everything is ok.
> [image: image]
> <https://cloud.githubusercontent.com/assets/15010186/15678592/951a7916-2757-11e6-9ee5-fb841657df57.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/islemag/issues/164#issuecomment-222711501>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DDtAMYxIcvkNU8fLh2jS76qubc2qks5qHEm_gaJpZM4Ipuzx>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by rodica-andronache** [comment]
This doesn't seem to be fixed http://dev2.themeisle.com/islemag/2014/11/24/iphone-6-plus-review/

**Comment by abaicus** [comment]
Pentru ca nu era nimic de reparat. Aici erau tagurile bagate din visual editor.

**Comment by rodica-andronache** [comment]
ok, am inteles :D
