### ISSUE TITLE
Hide section

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/islemag#172]
@cristian-ungureanu We have an issue with the sections. Some clients want to hide a section from Frontpage but we don't have this option. I think we should create something like on Parallax One.

@ineagu what do you think about that? Should we do that? I think is important to integrate this feature in our free version.

**Comment by ineagu** [comment]
what if they don't add a category on a specific section ? it won't dissaper
?

On Tue, Jun 21, 2016 at 1:02 PM, Madalin Milea <notifications@github.com>
wrote:

> @cristian-ungureanu <https://github.com/cristian-ungureanu> We have an
> issue with the sections. Some clients want to hide a section from Frontpage
> but we don't have this option. I think we should create something like on
> Parallax One.
>
> @ineagu <https://github.com/ineagu> what do you think about that? Should
> we do that? I think is important to integrate this feature in our free
> version.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/islemag/issues/172>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DGEd8huMOFiL_dOAAuBXj9P3mLuGks5qN8S4gaJpZM4I6m-E>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by mileamadalin** [comment]
@ineagu You can't do that because you have no possibility to select "none".  You have to choose between all categories or one of them.

**Comment by ineagu** [comment]
ok, we can leave this open, however I don't think is important enough for
now.

On Tue, Jun 21, 2016 at 2:36 PM, Madalin Milea <notifications@github.com>
wrote:

> @ineagu <https://github.com/ineagu> You can't do that because you have no
> possibility to select "none". You have to choose between all categories or
> one of them.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/islemag/issues/172#issuecomment-227426243>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DItP8XHlz_0OP8I7k4MRzdzfry4Aks5qN9rEgaJpZM4I6m-E>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by silvia-b** [comment]
Hi, I have just installed Islemag theme (see http://www.quartcassolacentro.provahosting.it/) and realized that sections cannot be hidden. I think this should be implemented: sometimes one just does not have enough material to fill all sections.

Can you suggest me something to improve my website without doing everything from the beginning?

Thanks a lot!

**Comment by rodica-andronache** [comment]
Hi @silvia-b ,

I'm going to close this issue, as we have another one created for this problem, but we'll work on adding options to hide all the frontpage sections, in the next update.

Regards,
Rodica

**Comment by silvia-b** [comment]
ok, thanks Rodica

Il 14/10/2016 15:39, Rodica-Elena Andronache ha scritto:
