### ISSUE TITLE
Instagram Feed issue

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/islemag#174]
@cristian-ungureanu We have an issue with the Instagram feed:

<img width="482" alt="screen shot 2016-07-04 at 10 32 56 pm" src="https://cloud.githubusercontent.com/assets/6906834/16569514/a9968146-4237-11e6-826d-a9b88cc3fa09.png">

**Comment by rodica-andronache** [comment]
@mileamadalin does this have anything to do with the theme?

**Comment by mileamadalin** [comment]
@rodica-andronache yep, because with another theme the plugin works

**Comment by claudiuvertistudio** [comment]
It looks like token expired. https://smashballoon.com/my-instagram-access-token-keep-expiring/

**Comment by rodica-andronache** [comment]
@mileamadalin can you please fix this on demo? http://prntscr.com/cg1d91

**Comment by mileamadalin** [comment]
@rodica-andronache Yep, I will fix it. this week.

**Comment by rodica-andronache** [comment]
@mileamadalin how is this going? :D

**Comment by mileamadalin** [comment]
@rodica-andronache Done!
