### ISSUE TITLE
Owl Carousel bugs Humbugger menu

### ISSUE THREAD

**Issue by Basilakis** [Codeinwp/islemag#176]
For those who deal an issue with ShopIsle and menu not loading, there is a problem with Own Carousel, when it has 1 slider inside and loop: true and items: 1

That makes the JS console to return the issue Uncaught TypeError: Cannot read property ‘clone’ of undefined and bug the humbugger also, as it is JS.

I do not know if the solution is easy, because that is the way to register own carousel.

**Comment by Basilakis** [comment]
I avoided using special CSS on single slides using this code:

```
var owl = $('.header-slider');
          owl.owlCarousel({
            nav: owl.children().length > 1,
            navText: ["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],
            pagination: false,
            items: 1,
            autoplay: false,
            autoplaySpeed: 500,
            loop: owl.children().length > 1
          });

```
the problem occurs only when loop is enabled, so i disable loop and nav when there is only one item. The slider gets initialized without errors.

That seems to be the solution, I digged the issue a bit here
https://github.com/OwlCarousel2/OwlCarousel2/issues/539

**Comment by rodica-andronache** [comment]
@Basilakis is this for ShopIsle or Islemag? :D

**Comment by Basilakis** [comment]
Really sorry, u are right, Shopeisle.
Want me to move it?
On Wednesday, 6 July 2016, Rodica-Elena Andronache <notifications@github.com>
wrote:

> @Basilakis <https://github.com/Basilakis> is this for ShopIsle or
> Islemag? :D
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/islemag/issues/176#issuecomment-230898924>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAR7VTbfDkzi0lvFzNB7AGszvxpq3gK9ks5qTBJQgaJpZM4JFZ5G>
> .
>


-- 
Kanonidis Basilis
creativeG.gr  - http://www.creativeg.gr
creative και interactive studio
mobi: +30 6934329805
tel: +30 2310 907272

**Comment by rodica-andronache** [comment]
Yes, you can move it. Thanks :)

**Comment by rodica-andronache** [comment]
@Basilakis I moved it :)
