### ISSUE TITLE
[feature request] Mobile Adspace Below Menu

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/islemag#177]
User scenario was that people might not scroll right down to the bottom of the page so might not get exposed to their ads

**Comment by rodica-andronache** [comment]
@UVLabs if you see more requests for this, mention here please :)

**Comment by UVLabs** [comment]
@rodica-andronache I think most users would just settle for not having that feature if they don't see it. Maybe we could get the opinion of @mariusghitulescu

**Comment by mariusghitulescu** [comment]
I would suggest to keep it right under the slider for mobile, seems like a good position easy to spot, without being to spammy.

**Comment by rodica-andronache** [comment]
yeah, it's a good idea, but I think it's not very easy to implement. That's why I'm not sure if we can do this, and when
