### ISSUE TITLE
Mobile View

### ISSUE THREAD

**Issue by 33akash** [Codeinwp/islemag#178]
Menu button is not working while viewing the webpage in mobile and also Section 5 and Section 3 shows no articles.

**Comment by rodica-andronache** [comment]
Hi @33akash ,

Thank you for contacting us. I tried to replicate your issues, but didn't manage to do this, so I think there must me something else, rather then a bug in the theme. Please contact us here http://themeisle.com/contact/ for issues like this, as we try to keep Github only for bug reporting/enhacements.

Thank you for understanding,
Rodica
