### ISSUE TITLE
Indicator open/closed pe widget de ad

### ISSUE THREAD

**Issue by cristianraiber** [Codeinwp/islemag#181]
![pasted image at 2016_07_25 12_11 pm](https://cloud.githubusercontent.com/assets/7841556/17101305/79250e88-527c-11e6-9fba-0a6ce2d9a2dd.png)

**Comment by cristianraiber** [comment]
@rodica-andronache - Ar merge folosit acelasi mark-up ca al default WP pt. a avea indicator de open/closed (vezi widget-ul parinte ca are indicator).

**Comment by rodica-andronache** [comment]
@cristianraiber da, o sa adaugam asta la un moment dat. Mersi de sugestie
