### ISSUE TITLE
CSS Bug :: Widget - Tag Cloud :: Styling

### ISSUE THREAD

**Issue by cristianraiber** [Codeinwp/islemag#182]
@rodica-andronache - Vezi: https://github.com/Codeinwp/islemag/blob/production/style.css#L3669.  Acel !important suprascrie ce pune WP-ul pt. a controla font-size-urile tag-urilor. AKA: Nu se afiseaza in Tag Cloud tag-ul care este folosit mai des cu un font-size mai mare :)

**Comment by rodica-andronache** [comment]
it looks really bad with this change, so I think it's better to leave it like this
