### ISSUE TITLE
Overwriting the parent recommended actions/plugins

### ISSUE THREAD

**Issue by cristianraiber** [Codeinwp/islemag#183]
@rodica-andronache  - Vezi, aici: https://github.com/Codeinwp/islemag/blob/production/functions.php#L120-L147. Ar fi fost ideal ca liniile astea sa fie intr-o functie wrapp-uita intr-un `!function_exists` ... Avem nevoie sa adaugam din tema child un alt plugin recommended si o alta actiune (poate veti mai avea si voi nevoie :) ) si nu avem cum s-o facem fara sa suprascriem tot functions.php

**Comment by ineagu** [comment]
stiu, tre sa refacem toata treaba asta cu about page mai modular, sa poti din plugin sa adaugi notificari/sau sa scoti .

deocamdata e ok sa pui cu tgm.
