### ISSUE TITLE
Header Banner Display Bug

### ISSUE THREAD

**Issue by cristianraiber** [Codeinwp/islemag#188]
https://github.com/Codeinwp/islemag/blob/production/style.css#L3589. Aici e gresit viewport-ul.

Practic, acum sunt 728px(latimea banner-ului) - 600px(viewport-ul) =  128px in care bannerul este afisat. Un viewport care cred c-ar fi mai bun ar fi 768px (si mai standard :) )

**Comment by claudiuvertistudio** [comment]
cred ca e ok acum
