### ISSUE TITLE
thirdparty comment counter

### ISSUE THREAD

**Issue by 33akash** [Codeinwp/islemag#194]
There is no support for third-party comment counter. I am using Facebook comments. It shows 0 comments as i have disabled the wordpress comments and using Facebook comments.

**Comment by 33akash** [comment]
WEBSITE : http://lutalica.in

Yes i am using Facebook comments plugin : https://wordpress.org/plugins/facebook-comments-plugin/

**Comment by rodica-andronache** [comment]
Hi @33akash ,

Thank you for the details. We'll try to investigate this.
Could you please also let me know if have used this plugin with any other theme and it was working correctly.

Regards,
Rodica

**Comment by 33akash** [comment]
Hello,
No i have not used this plugin with any other theme.

Thank you.

**Comment by 33akash** [comment]
![for the people of the night lutalica](https://cloud.githubusercontent.com/assets/6785628/18813803/2fee01d8-8324-11e6-9ec2-2d42add2646a.png)
![home lutalica](https://cloud.githubusercontent.com/assets/6785628/18813804/3018ebb4-8324-11e6-864a-61bc245e5cdd.png)

**Comment by rodica-andronache** [comment]
Hi,

We'll try to investigate this in the next weeks, but meanwhile, you could also try to see if the plugin is working well with other themes, so we know there is not an issue specific to the plugin.

Regards,
Rodica
