### ISSUE TITLE
Section disable option

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/islemag#195]
@rodica-andronache

**Comment by UVLabs** [comment]
+1

**Comment by rodica-andronache** [comment]
Add a "Disable section" option for each of the 5 frontpage sections. Keep the string "Disable section" the same for each section, to only have one untranslated string. And don't add any description to the option

**Comment by rodica-andronache** [comment]
@cristian-ungureanu I'm not sure if it's because of this commit or maybe the issue you mentioned on other themes, with the icon picker, but the customizer is not loading anymore (or really really slow )

**Comment by cristian-ungureanu** [comment]
@rodica-andronache I changed the icon picker for customizer. (https://github.com/Codeinwp/islemag/pull/200). It should work better now,
