### ISSUE TITLE
Logo not showing on tablet

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/islemag#205]
The logo doesn't display on tablet in portrait view, it shows only the ad @rodica-andronache

**Comment by claudiuvertistudio** [comment]
@UVLabs sorry, but a don't see the problem here. Can you provide me some images and give me more details?

**Comment by rodica-andronache** [comment]
@UVLabs I coudn't replicate this either. Please provide more details

**Comment by UVLabs** [comment]
Not able to reproduce it also
