### ISSUE TITLE
Large amount of image sizes

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/islemag#219]
@rodica-andronache I uploaded an image with Islemag installed and it made 23 variations of the images, is this intentional? We have a customer querying about it.

**Comment by rodica-andronache** [comment]
@UVLabs yes, we have many image sizes to fit all the sections custom dimensions

**Comment by stuckathomemom** [comment]
Yes, far to many image sizes and this is a HUGE ISSUE!
Bloggers, especially How To blogs, can put up to 20 images in each post. If I put 20 images in a post and the theme creates 20 different image sizes for each image, that is 400 images with only 20 actually used. 
That's 400 images that are eating up valuable server space. 

This problem needs to be corrected. I have edited out several lines in the functions.php file as a very sloppy patch, but this needs to be fixed.
