### ISSUE TITLE
Menu doesn't collapse on mobile

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/islemag#224]
If 'Disable sticky menu' option is enabled, the console will throw:

```TypeError: stickyNav is not a function```

Because the function is defined under a parent function, but then is used outside of it.

@rodica-andronache

**Comment by UVLabs** [comment]
+1

**Comment by UVLabs** [comment]
+1

**Comment by rodica-andronache** [comment]
Fixed here https://github.com/Codeinwp/islemag/commit/12de457cb91339e8d0a229bfaa671ae6e7ae44a5
