### ISSUE TITLE
Advertisement areas not working - IsleMag Widgets

### ISSUE THREAD

**Issue by roseyazman** [Codeinwp/islemag#227]
ezyfun.com is my site. I have tried to enter code of advertisement in Advertisement area 2, 3, 4 and 5 all these areas are not being displayed on my site. 
waiting for an early response.
regards
![ad areas not working](https://cloud.githubusercontent.com/assets/26060178/23548486/901efb2a-0029-11e7-9962-f33826be7b69.png)

**Comment by rodica-andronache** [comment]
Hi @roseyazman ,

I'm sorry for the late reply. I tested on my local site and everything seems alright. I think the reason that you may not see the advertisement areas is because you are using Adblock or something else, that hides advertisements in the browser.

Regards,
Rodica

**Comment by funashi** [comment]
On my site https://lensesview.com the code inserted into the Header Widget does not display the adverts but instead display the actual "Ad Code"
<img width="1250" alt="screen shot 2017-06-13 at 12 54 09 pm" src="https://user-images.githubusercontent.com/14979536/27079332-7c517b00-5037-11e7-98d6-aeab572c0ce5.png">

**Comment by amritachary** [comment]
@rodica-andronache I have the same bug as @funashi .Please provide some sort of assistance or fix.

**Comment by evilsoldier** [comment]
Simillar issue here. I cannot see Header Advertisement Area in posts. It is visible on all pages, but when i go into some post, Header Advertisement Area is gone.

**Comment by rodica-andronache** [comment]
Hi there,

The 'Header advertisement area' Sidebar is called on all pages, so there shouldn't be a problem, not appearing on single post pages. Make sure you are not using Adblock or something else, that hides advertisements in the browser, and if you are using the "Islemag - Content advertisment widget" widget, you can try the add code you are using in a normal Text widget. This way you can test and see if the code you are using is correct.

Regards,
Rodica
