### ISSUE TITLE
Advertisement widgets are not working 

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/islemag#230]
@rodica-andronache  The advertisement widgets are not working properly. When someone pastes the code and as soon as hit the save button, it modifies some part of the code.

https://secure.helpscout.net/conversation/364911493/133203/?folderId=212390

**Comment by poonam279** [comment]
+1 https://secure.helpscout.net/conversation/367848765/133636/?folderId=212385

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , this should be fixed now.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu you left a var_dump() in islemag-widget-multiple-ads.php
Also, I don't understand how those widgets are working either. I added some widgets there, but I can't see them anywhere

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , remove the var_dump ... as for widgets, you need to have adsense and some banners to display them there. The problem was that when I sanitized the code. I didn't accept some style and some parameters for google adsense code.

**Comment by HardeepAsrani** [comment]
I noticed that when post something in the "Advertisement Area 1" and "Advertisement Area 2" - the same content from "Advertisement Area 1" shows up in both places. If there's nothing placed in "Advertisement Area 1" and only placed in AREA 2 - then nothing shows up.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu please check this
