### ISSUE TITLE
Page title should be in h1 tag

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/islemag#238]
@bogdanpopa90 Islemag theme is using H2 tag in the page for heading rather than h1.

HS: https://secure.helpscout.net/conversation/430089696/142750/?folderId=212385

**Comment by bogdanpopa90** [comment]
Fixed on single post

**Comment by bogdanpopa90** [comment]
- Added support for hAtom/hEntry
- Changed H1 logo, it will be only on frontpage
