### ISSUE TITLE
Related posts hiding not SEO friendly

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/islemag#242]
@rodica-andronache on islemag when you select Hide Related posts, it simply adds a class that has display: none rather than not outputting anything at all

**Comment by rodica-andronache** [comment]
@radu-themeisle when you have some time, you can tackle this too. What's happening now, is that here https://github.com/Codeinwp/islemag/blob/9aa5bdfc0c5c15093cce406c6cb247367db4e45d/template-parts/content-single.php#L160 the option to hide the related posts from the customizer 'islemag_single_post_hide_related_posts' is adding an 'islemag_hide' class to that area, adding display: none to that section.
What you need to do is have a big if, where you check if that islemag_single_post_hide_related_posts is selected. And if so, you just don't display that whole div.
We can talk if there are things unclear 👍
