### ISSUE TITLE
Submenu doesn’t scroll

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/islemag#245]
Long submenu does not scroll vertically after sticky navigation gets activated. 

Relevant forum link: https://wordpress.org/support/topic/submenu-doesnt-scroll/

**Comment by Vishakha-Patel** [comment]
@rodica-andronache

**Comment by rodica-andronache** [comment]
@Vishakha-Patel for me it's seems to work. Did you check on a certain browser? Could you please give me a screenshot maybe?

**Comment by Vishakha-Patel** [comment]
I am checking on Windows 8, Chrome. Sure. I am attaching a screenshot.

![menu 2](https://user-images.githubusercontent.com/29881234/33767581-2cf528ac-dc48-11e7-9d8e-359e1efe06f9.png)
![menu 3](https://user-images.githubusercontent.com/29881234/33767582-2d352736-dc48-11e7-9f9b-83e3b65ea486.png)

**Comment by rodica-andronache** [comment]
@Vishakha-Patel ok, I understood now 👍 We'll have to investigate, though it's not something with high priority
