### ISSUE TITLE
Alt attributes to images

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/islemag#251]
A lot of images need alt attributes in there. @rodica-andronache

**Comment by rodica-andronache** [comment]
@radu-themeisle you can try to give this a try when you have some time. Is not urgent. 
First, you need to check if/what are the images that need the alt tag.
The main idea is to make sure images that are uploaded from customizer, get their alt tag using the Alt Text option of the image https://prnt.sc/jr27wp
You can check https://github.com/Codeinwp/hestia-pro/pull/1284/commits/6f9a8aba6d745b709f8776db8542e8afa375703f
https://github.com/Codeinwp/hestia-pro/pull/1284/commits/c0e1383aea9921a34646591e0bb92b2b2b02575e
We can talk if you need more info 👍
