### ISSUE TITLE
 style.css ¿../image/404bg.jpg?

### ISSUE THREAD

**Issue by oldlastman** [Codeinwp/islemag#254]
on style.css line 5784
`background-image: url("../images/404bg.jpg");`

this constantly give me 404 on my instalation

¿is necesary? or ¿is legacy bug?

thanks

**Comment by rodica-andronache** [comment]
@oldlastman I think this is a bug, maybe @radu-themeisle can have a look when he can

**Comment by radu-themeisle** [comment]
@oldlastman thank you for your message. I didn't get any errors on instalation however the CSS code is not in use so we've removed it and it will be fixed in a future update.
Meanwhile, you can delete the line or the whole CSS class from styles.css and everything should work properly.
