### ISSUE TITLE
index.php shows wrong posts

### ISSUE THREAD

**Issue by justintadlock** [Codeinwp/islemag#33]
The `index.php` template is the fallback template if no better template can be found.  It should always show the main query and loop.  Otherwise, the theme breaks all kinds of plugins.

I'm assuming this is meant to show a custom front page.  WordPress has 2 methods for this:

1) Create a custom page template that users can assign to their pages.
2) Create a custom `front-page.php` and show your custom stuff if Settings > Reading > Front Page Displays is set to show a "page" on the front.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu is this fixed? if so, please close the issue
