### ISSUE TITLE
Yellow overlay is too bright.

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/islemag#65]
![image](https://cloud.githubusercontent.com/assets/15010186/12356255/4e973e48-bbaa-11e5-82cd-9a176cb74fe7.png)

**Comment by ineagu** [comment]
agree, but please send also the color that you think would suit better

**Comment by abaicus** [comment]
I'd suggest something like this.
![image](https://cloud.githubusercontent.com/assets/15010186/12445673/61945568-bf6e-11e5-9f05-8786a9fe9cac.png)

The color is: #FF6B6B / rgb(255,107,107)

**Comment by ineagu** [comment]
there is not another red one ?

On Wed, Jan 20, 2016 at 11:08 AM, abaicus <notifications@github.com> wrote:

> I'd suggest something like this.
> [image: image]
> <https://cloud.githubusercontent.com/assets/15010186/12445673/61945568-bf6e-11e5-9f05-8786a9fe9cac.png>
>
> The color is: #FF6B6B / rgb(255,107,107)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/islemag/issues/65#issuecomment-173154150>.
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by abaicus** [comment]
Yes.

![image](https://cloud.githubusercontent.com/assets/15010186/12445849/627a0b16-bf6f-11e5-9330-71023371ab54.png)


At the moment we've got two yellow as well.

![image](https://cloud.githubusercontent.com/assets/15010186/12445856/6e5541c6-bf6f-11e5-9e4e-a1b998c3d0f5.png)

**Comment by ineagu** [comment]
ok, got it , you can try the new one cristi and see how it looks like
overall

On Wed, Jan 20, 2016 at 11:15 AM, abaicus <notifications@github.com> wrote:

> Yes.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/15010186/12445849/627a0b16-bf6f-11e5-9330-71023371ab54.png>
>
> At the moment we've got two yellow as well.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/15010186/12445856/6e5541c6-bf6f-11e5-9e4e-a1b998c3d0f5.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/islemag/issues/65#issuecomment-173158389>.
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by cristian-ungureanu** [comment]
looks good :)
