### ISSUE TITLE
Overlay size is not consistent.

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/islemag#66]
The overlay should have the same height even if there is no content in it. 

![image](https://cloud.githubusercontent.com/assets/15010186/12356319/a49aff1e-bbaa-11e5-9e43-7bef8de6c955.png)

**Comment by ineagu** [comment]
not a big issue, probably it won't be the case.

**Comment by cristian-ungureanu** [comment]
@abaicus , that's because that post don't have a title.
