### ISSUE TITLE
Search area is unintuitive.

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/islemag#67]
I would suggest making the search field appear on hover over the search icon and for it to be near the search icon.

**Comment by ineagu** [comment]
agreed, if it takes more than 30 minutes, remove the top icon completely from free version

**Comment by cristian-ungureanu** [comment]
@ineagu , how about this? 
![screenshot_1](https://cloud.githubusercontent.com/assets/9929553/12447052/63fe1584-bf76-11e5-839b-6d4f064ad8ab.png)

**Comment by ineagu** [comment]
it may be ok ( how it looks when there is a banner there ?

On Wed, Jan 20, 2016 at 12:04 PM, cristian-ungureanu <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> , how about this?
> [image: screenshot_1]
> <https://cloud.githubusercontent.com/assets/9929553/12447052/63fe1584-bf76-11e5-839b-6d4f064ad8ab.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/islemag/issues/67#issuecomment-173172616>.
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by cristian-ungureanu** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/9929553/12459436/5e399894-bfb7-11e5-8db9-f3c746326dd1.png)
