### ISSUE TITLE
Allow users to select the colors that randomly appear on the post overlay.

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/islemag#68]
We should at least give them the option to select the colors even if they appear randomly. Same for the primary menu. This would give the opportunity to achieve a more unified appearance.

Later Edit: This could also be one of the PRO features.

**Comment by ineagu** [comment]
this is not a priority, can be done later on, if users are asking it.

**Comment by clemorphy** [comment]
This guy was asking for it : https://wordpress.org/support/topic/edit-colors-in-islemag-theme/
It would be useful to me too.
I don't really like those default colors and they don't even seem to be related to categories or tags.
