### ISSUE TITLE
Widget section for banner 

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/islemag#91]
@rodica-andronache @cristian-ungureanu We should add a widgets area in our top header instead Banner type; position, Image and link. 

![skitch 2](https://cloud.githubusercontent.com/assets/6906834/13061619/255a64a4-d439-11e5-9ac3-c947cf786589.png)

In this way, the customers can add the banner more simple and we will avoid the complications that can occur with the Theme Review Team (from wp.org)

**Comment by cristian-ungureanu** [comment]
@mileamadalin , @ineagu I think it's easier for users to add/change the banner from customizer. I think that if there is a problem with this implementation, we'll have the same problem even if we add there a sidebar and make a custom widget...I think they'll ask this in a plugin.

**Comment by ineagu** [comment]
there are 3 issues : 

1. They don't allow js/css in customizer, due to security/sanitization stuff for themes
2. Users are used in this way, all themes are doing like this, like in zerif you can have the widget area directly in that section in customizer, so people can do it there
3.Image setting is a bit useless without a link.

**Comment by cristian-ungureanu** [comment]
Should I remove the repeater for social links too and implement it with widgets?

**Comment by ineagu** [comment]
no, we can keep it and see if there are issues.

On Mon, Feb 22, 2016 at 2:06 PM, cristian-ungureanu <
notifications@github.com> wrote:

> Should I remove the repeater for social links too and implement it with
> widgets?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/islemag/issues/91#issuecomment-187162713>.
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
