### ISSUE TITLE
WPPR feature

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/islemag#93]
@rodica-andronache @cristian-ungureanu we can add a condition --- when a customer has the WPPR plugin on his website, we can add the product note on the image. 

![skitch 5](https://cloud.githubusercontent.com/assets/6906834/13062076/34cbe8f6-d43c-11e5-9d92-c9a9dbd05301.png)

I attached you an image with a possible position.

**Comment by cristian-ungureanu** [comment]
@ineagu , what do you think about this? I can't find a place for this.

**Comment by ineagu** [comment]
@cristian-ungureanu not sure how it looks, we can also use stars and add them like on sahifa : http://themes.tielabs.com/sahifa/ , for example in the architecture section, we can add them after the title

**Comment by cristian-ungureanu** [comment]
@ineagu , how about this: http://prntscr.com/a6lt99 ?
Should I remove the "Rating:" label? On first section I think it's a little bit empty without it.

**Comment by ineagu** [comment]
looks quite ok, see with andrei how it might work the best with spacing

On Mon, Feb 22, 2016 at 6:53 PM, cristian-ungureanu <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> , how about this:
> http://prntscr.com/a6lt99 ?
> Should I remove the "Rating:" label? On first section I think it's a
> little bit empty without it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/islemag/issues/93#issuecomment-187292750>.
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
