### ISSUE TITLE
WPPR Add-on issue

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/islemag#94]
@rodica-andronache @cristian-ungureanu I tried to activate the Pro version of WPPR on IsleMag theme and I noticed an issue. On the post page, my text is white and when I select "yes" from "Is this a review post?" nothing happens.

![skitch 6](https://cloud.githubusercontent.com/assets/6906834/13062299/d9dd90a0-d43d-11e5-93e9-a701cceaa2bb.png)

The problem is that; with the Add-On enabled I could not add a new review for a product. I tested on Mac; Safari & Chrome.

**Comment by cristian-ungureanu** [comment]
@mileamadalin , can you check this again? I think it was a problem with WPPR.
